import type { OfficeConfig } from '@/types';

// World Relief U.S. office configs. Voice/audience fields are VERBATIM from each
// director's questionnaire (Microsoft Forms export, 2026). Operational fields
// (director title/phone, givingUrl, signatureBlock) were NOT in the questionnaire
// and are left blank until World Relief supplies them — the app flags rather than
// invents them. givingUrl '' disables the giving-link swap for that office.

export const offices: OfficeConfig[] = [
  {
    id: "western-washington",
    name: "World Relief Western Washington",
    director: {
      name: "Medard Ngueita",
      title: "Executive Director",
      email: "MNgueita@wr.org",
      phone: "",
    },
    givingUrl: "",
    signatureBlock: "",
    audienceReligious: "Our audience is highly mixed.",
    audiencePolitical: "Overall, our area is progressive and leans strongly liberal. However, the Whatcom area leans more conservative than the other two offices. Because of the contentious nature between the two main political parties and because a certain “flavor” of Christianity is seen as a common trait of ultra conservatives, Christians/Christianity is sometimes regarded negatively by many our area.",
    politicalPhrasesToAvoid: "We avoid partisan language, especially language that solely blames a political party for a certain action or situation. Medard very clearly calls out injustices and myths about immigrants but is careful.",
    preferredBiblicalPhrases: "Medard always gives thanks to God for the blessings that we have and using those blessings to help others. He is always sure to reference Scripture as a grounding for the ideas he presents.",
    preferredBibleVerses: "Micah 6:8\n\nMatthew 25:35\n\nEcclesiastes 4:9-10\n\nPhilippians 2: 3-4\n\nLuke 5",
    faithPhrasesToAvoid: "We avoid blaming a particular denomination or group for a situation.",
    programming: "Resettlement; Extended Case Management; Immigration Legal Services; Children & Family Services; ESL Services; Employment Services; Resiliency Services – community garden, environmental education, commercial & teaching kitchen; Detention Center Ministry",
    distinctive: "WRWW’s holistic approach to caring for refugees and immigrants sets our work apart, providing not only practical care, but also meeting the emotional and spiritual needs of our participants. Our partnership with the church is also distinctive in this area, as most other organizations in the region are either non-religious or intentionally multi-religious. We also believe in diversity and representation of those we serve and who is on staff, as a foundation for community trust.",
    accomplishments: "We are proud of the resiliency of our staff throughout these heavy, discouraging, and contentious times. Even with a large layoff last year and the restructuring of our office/business model to move away from mostly resettlement to focusing on other areas, the staff has remained steadfast and has continued to provide excellent care to our participants.\n\nWe are also proud of the incredible ways in which we have been able to increase our donor base and appeal to our existing donors, which has allowed us to quickly expand our team, especially ILS, to meet the increasing needs of the immigrants in our area.",
    sentenceStyle: "Medard generally is more narrative, but he uses shorter sentences to emphasize a particular point. This contrast makes the shorter sentence more impactful.",
    celebrationTone: "Medard begins by praising God for his gracious provision. He also is careful to recognize the staff and volunteers that help make success possible. His tone is enthusiastic, gracious, humble, and thankful.",
    crisisTone: "Medard uses a serious tone, but he always leans into the faith that God will provide, the hope that God will do more than we can ever imagine, and the call to discern how God wants us to act/respond to the crisis.",
    financialAskStyle: "Medard creates a compelling vision of what God is calling us into and then invites people into action. EX: “Let us continue to be the kind of people who don’t just witness suffering—but respond. Who don’t just admire resilience—but invest in it.”\n\nHe also emphasizes giving as a partnership in the work that we are doing rather than “charity.”\n\nMedard provides specific metrics to show what we’ve been able to do, what we hope to do in the future, and what we can do with a certain amount raised.",
    personalAnecdotes: "Medard often speaks of some of his own personal experiences, including growing up in hardship in Chad, arriving in the U.S. with his wife as an asylum seeker, and the help that World Relief provided after they arrived. He also speaks of his work at World Relief prior to becoming the Executive Director.",
    outOfCharacterTone: "A tone of anger, frustration, or feeling overwhelmed would feel uncharacteristic. It would also feel odd if he was too serious or too silly – any extreme would be uncharacteristic.",
    active: true,
  },
  {
    id: "chicagoland",
    name: "World Relief Chicagoland",
    director: {
      name: "Susan Sperry",
      title: "",
      email: "ssperry@wr.org",
      phone: "",
    },
    givingUrl: "",
    signatureBlock: "",
    audienceReligious: "Wide continuum, including evangelical churches, mainline churches, Catholic. We tend to be \"religiously central\" in what we write, and only somewhat faith forward (we think about 1-2 mentions of faith in each newsletter, not overly preachy)",
    audiencePolitical: "A wide continuum, but mostly center-left and center-right (moderate)",
    politicalPhrasesToAvoid: "•\toverly patriotic language\n–\texample: American dream, “our great country”\n•\tphrases that would make a former client feel uncomfortable if they read it\n–\texample: immigrants come with so many needs, and you can help them get on their feet\n•\tlanguage with politically charged/partisan overtones\n–\t”unwelcoming policies” is generally better than “harsh” or “dehumanizing policies\n–\tsoften “Food Stamps” to “Food aid” or “Food support”\n\n\nThis isn't asked, but here is some “this, not that” phrase guidance:\n•\tpartners, rather than donors\n•\tfamilies or people, rather than clients\n•\twalk with, rather than serve, support, help",
    preferredBiblicalPhrases: "-\tJustice oriented\n-\tHope\n-\tWelcome\n-\tStability\n-\tPartnership\n-\tHope\n-\tCommunity\n-\tFaithfulness\n-\tTogether\n-\tHuman dignity\n-\tGod's image\n-\tChurches responding\n•\tglimpse of Heaven\n•\tfriendship\n•\tawe and gratitude\n•\thuman beings created in God's image\n•\theartbreaking\n•\tboldly welcome\n•\tremain in peace\n•\tmoments of connection\n•\tpursue their calling\n•\tsteady belief",
    preferredBibleVerses: "-\tIsaiah 58\n-\tMicah 6:8\n-\tMatthew 25",
    faithPhrasesToAvoid: "- Blessing\n- being saved\n- overly \"insider\" language - - avoid language that assumes a common \"insider\" Christianity, and if I do need to use a word or phrase or concept that does, explain it. I want to be welcoming in tone and invite people who don't believe in Jesus to feel comfortable and welcome reading",
    programming: "- Immigration legal services, Adult Education (many incredible classes, including entrepreneurship, sewing for work, and foundations of literacy), initial resettlement, case management, workforce development (career pathways), children & youth programs (after school programming, summer clubs, case management), counseling center (individual therapy, group programming, equestrian-based therapy), volunteer engagement, church engagement\n- We can send a broader service overview separately, and in particular can send over specific program emphasis for FY27",
    distinctive: "-\tA whole-person approach to each of our program areas\n-\tAn emphasis on education and empowerment throughout all of our service delivery; we want each person we serve to know how to meet their needs and have access to resources, tools, and people in the future\n-\tOur work with the church and overall community engagement\n-\tTrying to move people who are undecided/ on fence about immigrants into a position of support – particularly people in the church",
    accomplishments: "-\tStrong in crisis response… responded to Afghan Evacuation by submitting lists of people who needed evacuation to Senators, and resettling people quickly through OAW. Mobilized around southern border arrival response, and Ukrainian arrivals\n-\tExcellent, state-recognized English language program\n-\tStrong legal support… growing this team\n- MORE TO COME!",
    sentenceStyle: "- Naturally uses longer sentences, but edits down to be shorter. Somewhat indirect in communication (usually review to strengthen to a more direct tone)",
    celebrationTone: "-\tWarm, always focused on the people who made success possible especially our clients -\tPastoral without sounding preachy  -\tHopeful while acknowledging difficult realities  -\tCommunity-oriented  -\tDeeply relational",
    crisisTone: "-\tSharing facts, not dramatizing, pointing people to what we can do to engage with it -\tCalm rather than alarmist  -\tFocused on dignity rather than pity",
    financialAskStyle: "- Tie financial support to specific mission and impact. If a story was told, tie the request to the story \"your gift will support families like X\"\n- Bold, not begging\n- Invitational, not coercive or manipulative",
    personalAnecdotes: "-\tAnything that has been seen/ done recently to experience our work\n-\tStories about personal interests/ hobbies\n-\tStories about background with WR\n-\tVery limited stories about family (only with permission)",
    outOfCharacterTone: "-\tBragging, disconnected from current events  -\tDistant from the people we serve -\tOverly formal  -\tBig words",
    active: true,
  },
  {
    id: "california",
    name: "World Relief California",
    director: {
      name: "Mark Dandeneau",
      title: "",
      email: "MDandeneau@wr.org",
      phone: "",
    },
    givingUrl: "",
    signatureBlock: "",
    audienceReligious: "Our donors and partners come from diverse religious backgrounds. In Sacramento and San Diego, they often lean ecumenical, focusing on social justice and systemic support. Modesto draws heavily from traditional, evangelical roots centered on personal charity and stewardship. Garden Grove connects diverse immigrant congregations, including Hispanic and Vietnamese churches, with local suburban parishes, all joined in a shared commitment to welcome those in need.",
    audiencePolitical: "Political views vary across our four regions. Sacramento and San Diego generally hold more progressive perspectives focused on advocacy and human dignity. Modesto is a more conservative community that values personal responsibility and local stewardship. Garden Grove is quite moderate, where different cultural backgrounds shape a practical, family-first approach. We find common ground by focusing entirely on our shared responsibility to care for our neighbors.",
    politicalPhrasesToAvoid: "We avoid partisan political jargon, policy debates, and divisive terms like \"open borders\" or \"illegal aliens.\" Instead, we frame our conversations around human dignity and practical community support. By focusing on the value of every individual rather than ideological talking points, we build unity and invite all people of goodwill to join us in helping newcomers settle safely.",
    preferredBiblicalPhrases: "I prefer using phrases like \"welcome the stranger,\" \"walk alongside those who are vulnerable,\" and \"love our neighbors as ourselves.\" These terms emphasize inclusion and shared accompaniment. They represent an invitation to practice practical hospitality and extend love to every person, recognizing that everyone we serve has inherent value and deserves our respect.",
    preferredBibleVerses: "I anchor our mission in Matthew 25:35, \"I was a stranger and you welcomed me,\" which highlights our duty to help newcomers. I also rely on Luke 10:27, the command to \"love your neighbor as yourself,\" and Leviticus 19:34, which reminds us to treat foreigners as our own citizens, recognizing our shared human journey.",
    faithPhrasesToAvoid: "I avoid rigid, exclusionary, or transactional religious language, such as \"saving the lost\" or phrases that create an \"us versus them\" mentality. Service should never feel conditional or coercive. Since our faith is expressed through walking humbly with people, we avoid any tone that makes our help seem like a transaction rather than an act of love.",
    programming: "We provide trauma informed and holistic wraparound care through immigration legal services, comprehensive case management—including CalAIM health coordination—and employment assistance. Our educational services include ESL, women's empowerment, cultural orientation, and driving preparation, alongside youth and teen programming. Beyond direct services, we lead local advocacy efforts and build strong church and community engagement. Through our Good Neighbor Teams, we mobilize local congregations and volunteer groups to walk alongside arriving families, helping them set up apartments and navigate their new neighborhoods. This comprehensive approach ensures newcomers receive reliable support at every stage of their transition.",
    distinctive: "What sets us apart is our complete, wraparound approach backed by decades of local experience. We do not just manage files; we walk alongside families through the entire process. Crucially, many of our staff members have lived experience as former refugees or immigrants themselves. This creates deep trust and understanding, moving our work beyond standard social services into real, community-driven support.",
    accomplishments: "We are proud of bringing our four offices together into a unified regional model to increase our efficiency. Over the past few years, we scaled our CalAIM healthcare integration, moved our San Diego office to a better location for clients, and helped thousands of newcomers find steady jobs and housing. These achievements reflect our focus on good stewardship and respecting those we serve.",
    sentenceStyle: "I prefer using longer, narrative sentences rather than short directives. A narrative style leaves room for context, empathy, and storytelling. It better reflects the complex journeys of the families we serve, allowing us to explain our mission and values clearly while keeping the human element at the center of our communication with donors and partners.",
    celebrationTone: "When celebrating success, I keep a humble tone that focuses on our staff rather than myself. They do the hard work on the ground every day to make our programs succeed. Celebrating accomplishments is a chance to show genuine gratitude for their dedication and to recognize that our progress comes from teamwork and shared commitment.",
    crisisTone: "In a crisis, I use a calm, steady, and reassuring tone. Instead of reacting with panic, our communication should offer stability while acknowledging people's valid worries. The goal is to balance empathy for the hardship with a quiet confidence that, by working together as a community, we can navigate difficult challenges safely.",
    financialAskStyle: "I look at financial support as a partnership rather than a transaction, focusing on building long-term relationships and mutual respect. Asking for funds is an invitation to work together. We respect our donors by showing them exactly how their gifts provide housing, jobs, and legal help, turning their financial support into a meaningful, collaborative effort.",
    personalAnecdotes: "I prefer sharing simple, personal stories, like having coffee with a newly arrived family or watching a staff member guide a client. I also draw from my own journey through foster care, which taught me the true meaning of hospitality and belonging, and my joy of woodworking, where patience shapes raw material into a strong, stable foundation. These reflections highlight our shared humanity and the steady work of building up a community together.",
    outOfCharacterTone: "An aggressive, overly corporate, or purely transactional tone would feel completely out of character for me. We should avoid language that sounds boastful or cold and numbers-driven. Our voice must never seem exclusionary or slick. It should always remain grounded, warm, and respectful of the real-life struggles and journeys of the people we serve.",
    active: true,
  },
];
